### ISSUE TITLE
interface conversion: tree.Node is main.FileNode, not *tree.Tree

### ISSUE THREAD

**Issue by donovanhubbard** [dlvhdr/diffnav#1]
When I try running this in a directory that has a lot of changes, it panics and I get the following stack trace

```
➜  diffnav-troubleshooting cat error.txt | diffnav
Caught panic:

interface conversion: tree.Node is main.FileNode, not *tree.Tree

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/debug/stack.go:26 +0x6
runtime/debug.PrintStack()
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/debug/stack.go:18 +0x1
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /Users/donovan/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.g
panic({0x1021dfaa0?, 0x140001a6000?})
        /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x124
main.buildFullFileTree({0x1400019a000, 0x2, 0x14000023eb8?})
        /Users/donovan/code/diffnav/filetree.go:162 +0x49c
main.ftModel.SetFiles({{0x1400019a000, 0x2, 0x2}, 0x0, 0x0}, {0x1400019a000?, 0x0
        /Users/donovan/code/diffnav/filetree.go:22 +0x4c
main.mainModel.Update({{0x1400015c000, 0x6f5}, {0x14000010470, 0x2, 0x2}, 0x0, {0x10220b118, 0x1400007c900}, {0x10220b148, 0x1400011ad88}, ...}, ...)
        /Users/donovan/code/diffnav/main.go:83 +0xd00
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x14000000120, {0x10220b0e8?, 0x140001250a0?}, 0x140000781c0)
        /Users/donovan/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.go:452 +0x6a8
github.com/charmbracelet/bubbletea.(*Program).Run(0x14000000120)
        /Users/donovan/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.go:593 +0x7f8
main.main()
        /Users/donovan/code/diffnav/main.go:176 +0x3a8
```

I was able to narrow the problem down to the following two files that have changed. Here is the git diff.
```
diff --git a/Makefile b/Makefile
index e5ea751..918a730 100644
--- a/Makefile
+++ b/Makefile
@@ -5,3 +5,7 @@ build:
 .PHONY: run
 run:
 	go run cmd/cli/main.go localhost
+
+.PHONY: test
+test:
+	go test ./pkg/tui
diff --git a/pkg/utils/logging.go b/pkg/utils/logging.go
deleted file mode 100644
index 50b1845..0000000
--- a/pkg/utils/logging.go
+++ /dev/null
@@ -1,71 +0,0 @@
-package utils
-
-import (
-	"encoding/json"
-	"os"
-	"strings"
-
-	"go.uber.org/zap"
-	"go.uber.org/zap/zapcore"
-)
-
-var Logger *zap.Logger
-var Sugar *zap.SugaredLogger
-
-func getLogLevel() zapcore.Level {
-	defaultLevel := zapcore.DebugLevel
-
-	envLevel := os.Getenv("LOG_LEVEL")
-
-	if envLevel == "" {
-		return defaultLevel
-	}
-	if strings.ToLower(envLevel) == "debug" {
-		return zapcore.DebugLevel
-	}
-	if strings.ToLower(envLevel) == "info" {
-		return zapcore.InfoLevel
-	}
-	if strings.ToLower(envLevel) == "warn" {
-		return zapcore.WarnLevel
-	}
-	if strings.ToLower(envLevel) == "error" {
-		return zapcore.ErrorLevel
-	}
-	if strings.ToLower(envLevel) == "panic" {
-		return zapcore.PanicLevel
-	}
-	return defaultLevel
-}
-
-func InitializeLogger() {
-
-	rawJSON := []byte(`{
-		"level": "fatal",
-		"encoding": "json",
-		"outputPaths": ["./mcdctl.log"],
-		"errorOutputPaths": ["./mcdctl.log"],
-		"encoderConfig": {
-			"messageKey": "message",
-			"levelKey": "level",
-			"levelEncoder": "lowercase"
-		}
-	  }`)
-
-	var cfg zap.Config
-	if err := json.Unmarshal(rawJSON, &cfg); err != nil {
-		panic(err)
-	}
-
-	cfg.Level.SetLevel(getLogLevel())
-
-	cfg.EncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
-	cfg.EncoderConfig.TimeKey = "timestamp"
-
-	Logger := zap.Must(cfg.Build())
-	defer Logger.Sync()
-
-	Sugar = Logger.Sugar()
-
-	Sugar.Info("Logging initialized")
-}
```
The delta tool seems to handle the git changes just fine.

**Comment by dlvhdr** [comment]
Fixed by https://github.com/dlvhdr/diffnav/commit/0bca3cafd301c0954e72dd7f9cde19d1ecef9a12
